version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always    
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: aps
      MARIADB_PASSWORD: aps
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1